from Interfaces.LHCOlympics import LoadLHCOlympics
from CutAndExport.CutFunctions import *
from CutAndExport.CutEvent import CutEvents

folderName = "a5"
fileHeader = "alpha5"
a0 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-0.lhco")
a1 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-1.lhco")
a2 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-2.lhco")
a3 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-3.lhco")
a4 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-4.lhco")
a5 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-5.lhco")
a6 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-6.lhco")
a7 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-7.lhco")
a8 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-8.lhco")
a9 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-9.lhco")
a10 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-10.lhco")
folderName = "a5b"
fileHeader = "alpha5-1"
b0 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-0.lhco")
b1 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-1.lhco")
b2 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-2.lhco")
b3 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-3.lhco")
b4 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-4.lhco")
b5 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-5.lhco")
b6 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-6.lhco")
b7 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-7.lhco")
b8 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-8.lhco")
b9 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-9.lhco")
b10 = LoadLHCOlympics("F:/PyworkingFolder/CutExperiment/_DataFolder/wwaa/" + folderName + "/" + fileHeader + "-10.lhco")

# alpha 1
# crossSection = [824.0, 786.5, 755.5, 733.3, 722.1, 718.5, 721.9, 734.7, 765.7, 786.8, 823.2]
# alpha 2
# crossSection = [736.9, 729.7, 726.4, 721.0, 719.4, 718.2, 719.0, 720.5, 726.3, 731.7, 738.0]
# alpha 3
# crossSection = [736.9, 728.4, 725.9, 720.6, 719.3, 718.5, 719.7, 722.0, 725.9, 732.2, 739.8]
# alpha 4
# crossSection = [723.4, 720.3, 721.2, 718.6, 718.8, 719.4, 719.4, 719.7, 721.0, 722.8, 726.4]
# alpha 4 b
# crossSectionb = [724.2, 720.7, 721.2, 718.8, 718.4, 719.7, 720.4, 719.0, 722.0, 721.4, 725.9]
# alpha 5
crossSection = [719.8, 718.9, 720.7, 718.1, 719.9, 717.7, 718.3, 717.8, 719.5, 717.8, 720.2]
# alpha 5 b
crossSectionb = [724.0, 723.3, 723.2, 722.9, 722.5, 722.3, 722.9, 722.4, 722.7, 723.6, 724.9]

print(a0.GetEventCount())
print(a1.GetEventCount())
print(a2.GetEventCount())
print(a3.GetEventCount())
print(a4.GetEventCount())
print(a5.GetEventCount())
print(a6.GetEventCount())
print(a7.GetEventCount())
print(a8.GetEventCount())
print(a9.GetEventCount())
print(a10.GetEventCount())
print(b0.GetEventCount())
print(b1.GetEventCount())
print(b2.GetEventCount())
print(b3.GetEventCount())
print(b4.GetEventCount())
print(b5.GetEventCount())
print(b6.GetEventCount())
print(b7.GetEventCount())
print(b8.GetEventCount())
print(b9.GetEventCount())
print(b10.GetEventCount())

jetNumberCut = JetNumberCut(1, [2])
leptonNumberCut = LeptonPMCut(False, 1, 1)

CutEvents(a0, jetNumberCut)
CutEvents(a1, jetNumberCut)
CutEvents(a2, jetNumberCut)
CutEvents(a3, jetNumberCut)
CutEvents(a4, jetNumberCut)
CutEvents(a5, jetNumberCut)
CutEvents(a6, jetNumberCut)
CutEvents(a7, jetNumberCut)
CutEvents(a8, jetNumberCut)
CutEvents(a9, jetNumberCut)
CutEvents(a10, jetNumberCut)
CutEvents(b0, jetNumberCut)
CutEvents(b1, jetNumberCut)
CutEvents(b2, jetNumberCut)
CutEvents(b3, jetNumberCut)
CutEvents(b4, jetNumberCut)
CutEvents(b5, jetNumberCut)
CutEvents(b6, jetNumberCut)
CutEvents(b7, jetNumberCut)
CutEvents(b8, jetNumberCut)
CutEvents(b9, jetNumberCut)
CutEvents(b10, jetNumberCut)

CutEvents(a0, leptonNumberCut)
CutEvents(a1, leptonNumberCut)
CutEvents(a2, leptonNumberCut)
CutEvents(a3, leptonNumberCut)
CutEvents(a4, leptonNumberCut)
CutEvents(a5, leptonNumberCut)
CutEvents(a6, leptonNumberCut)
CutEvents(a7, leptonNumberCut)
CutEvents(a8, leptonNumberCut)
CutEvents(a9, leptonNumberCut)
CutEvents(a10, leptonNumberCut)
CutEvents(b0, leptonNumberCut)
CutEvents(b1, leptonNumberCut)
CutEvents(b2, leptonNumberCut)
CutEvents(b3, leptonNumberCut)
CutEvents(b4, leptonNumberCut)
CutEvents(b5, leptonNumberCut)
CutEvents(b6, leptonNumberCut)
CutEvents(b7, leptonNumberCut)
CutEvents(b8, leptonNumberCut)
CutEvents(b9, leptonNumberCut)
CutEvents(b10, leptonNumberCut)

print(a0.GetEventCount())
print(a1.GetEventCount())
print(a2.GetEventCount())
print(a3.GetEventCount())
print(a4.GetEventCount())
print(a5.GetEventCount())
print(a6.GetEventCount())
print(a7.GetEventCount())
print(a8.GetEventCount())
print(a9.GetEventCount())
print(a10.GetEventCount())

vbfCut = StandardVBFCut(True, 180.0, 2.3)

CutEvents(a0, vbfCut)
CutEvents(a1, vbfCut)
CutEvents(a2, vbfCut)
CutEvents(a3, vbfCut)
CutEvents(a4, vbfCut)
CutEvents(a5, vbfCut)
CutEvents(a6, vbfCut)
CutEvents(a7, vbfCut)
CutEvents(a8, vbfCut)
CutEvents(a9, vbfCut)
CutEvents(a10, vbfCut)
CutEvents(b0, vbfCut)
CutEvents(b1, vbfCut)
CutEvents(b2, vbfCut)
CutEvents(b3, vbfCut)
CutEvents(b4, vbfCut)
CutEvents(b5, vbfCut)
CutEvents(b6, vbfCut)
CutEvents(b7, vbfCut)
CutEvents(b8, vbfCut)
CutEvents(b9, vbfCut)
CutEvents(b10, vbfCut)

molCut = MolCut(1, False, 500)

CutEvents(a0, molCut)
CutEvents(a1, molCut)
CutEvents(a2, molCut)
CutEvents(a3, molCut)
CutEvents(a4, molCut)
CutEvents(a5, molCut)
CutEvents(a6, molCut)
CutEvents(a7, molCut)
CutEvents(a8, molCut)
CutEvents(a9, molCut)
CutEvents(a10, molCut)
CutEvents(b0, molCut)
CutEvents(b1, molCut)
CutEvents(b2, molCut)
CutEvents(b3, molCut)
CutEvents(b4, molCut)
CutEvents(b5, molCut)
CutEvents(b6, molCut)
CutEvents(b7, molCut)
CutEvents(b8, molCut)
CutEvents(b9, molCut)
CutEvents(b10, molCut)

leptonCut = LeptonPMDotCut(0, False, -0.75)

CutEvents(a0, leptonCut)
CutEvents(a1, leptonCut)
CutEvents(a2, leptonCut)
CutEvents(a3, leptonCut)
CutEvents(a4, leptonCut)
CutEvents(a5, leptonCut)
CutEvents(a6, leptonCut)
CutEvents(a7, leptonCut)
CutEvents(a8, leptonCut)
CutEvents(a9, leptonCut)
CutEvents(a10, leptonCut)
CutEvents(b0, leptonCut)
CutEvents(b1, leptonCut)
CutEvents(b2, leptonCut)
CutEvents(b3, leptonCut)
CutEvents(b4, leptonCut)
CutEvents(b5, leptonCut)
CutEvents(b6, leptonCut)
CutEvents(b7, leptonCut)
CutEvents(b8, leptonCut)
CutEvents(b9, leptonCut)
CutEvents(b10, leptonCut)

print(a0.GetEventCount())
print(a1.GetEventCount())
print(a2.GetEventCount())
print(a3.GetEventCount())
print(a4.GetEventCount())
print(a5.GetEventCount())
print(a6.GetEventCount())
print(a7.GetEventCount())
print(a8.GetEventCount())
print(a9.GetEventCount())
print(a10.GetEventCount())
print(b0.GetEventCount())
print(b1.GetEventCount())
print(b2.GetEventCount())
print(b3.GetEventCount())
print(b4.GetEventCount())
print(b5.GetEventCount())
print(b6.GetEventCount())
print(b7.GetEventCount())
print(b8.GetEventCount())
print(b9.GetEventCount())
print(b10.GetEventCount())

lstSets = [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10]
lstSets2 = [b0, b1, b2, b3, b4, b5, b6, b7, b8, b9, b10]

for i in range(11):
    print(str((lstSets[i].GetEventCount() + lstSets2[i].GetEventCount())
              * ((0.2 * crossSection[i] + 0.8 * crossSectionb[i]) / 250000.0)) + ", ")
