import os

from Applications.AZ.ZGammaCuts import *
from CutAndExport.CorrelationFunctions import *
from CutAndExport.CutEvent import CutEvents
from CutAndExport.CutFunctions import *
from CutAndExport.FilterFunctions import *
from CutAndExport.Histogram import *
from CutAndExport.SpecialTest import *
from Interfaces.LHCOlympics import LoadLHCOlympics
from Interfaces.LesHouchesEvent import LoadLesHouchesEvent

# fm2-new-8.lhco has problem
# fm3-9 has problem

os.chdir("../../_DataFolder/za/fittings/ft9")
eventfileNameA = "ft9"
eventfileNameB = "ft9-new"

testEvent0 = LoadLHCOlympics(eventfileNameA + "-0.lhco")
testEvent1 = LoadLHCOlympics(eventfileNameA + "-1.lhco")
testEvent2 = LoadLHCOlympics(eventfileNameA + "-2.lhco")
testEvent3 = LoadLHCOlympics(eventfileNameA + "-3.lhco")
testEvent4 = LoadLHCOlympics(eventfileNameA + "-4.lhco")
testEvent5 = LoadLHCOlympics(eventfileNameA + "-5.lhco")
testEvent6 = LoadLHCOlympics(eventfileNameA + "-6.lhco")
testEvent7 = LoadLHCOlympics(eventfileNameA + "-7.lhco")
testEvent8 = LoadLHCOlympics(eventfileNameA + "-8.lhco")
testEvent9 = LoadLHCOlympics(eventfileNameA + "-9.lhco")
testEvent10 = LoadLHCOlympics(eventfileNameA + "-10.lhco")

testEvent0.AddEventSet(LoadLHCOlympics(eventfileNameB + "-0.lhco"))
testEvent1.AddEventSet(LoadLHCOlympics(eventfileNameB + "-1.lhco"))
testEvent2.AddEventSet(LoadLHCOlympics(eventfileNameB + "-2.lhco"))
testEvent3.AddEventSet(LoadLHCOlympics(eventfileNameB + "-3.lhco"))
testEvent4.AddEventSet(LoadLHCOlympics(eventfileNameB + "-4.lhco"))
testEvent5.AddEventSet(LoadLHCOlympics(eventfileNameB + "-5.lhco"))
testEvent6.AddEventSet(LoadLHCOlympics(eventfileNameB + "-6.lhco"))
testEvent7.AddEventSet(LoadLHCOlympics(eventfileNameB + "-7.lhco"))
testEvent8.AddEventSet(LoadLHCOlympics(eventfileNameB + "-8.lhco"))
testEvent9.AddEventSet(LoadLHCOlympics(eventfileNameB + "-9.lhco"))
testEvent10.AddEventSet(LoadLHCOlympics(eventfileNameB + "-10.lhco"))

print(testEvent0.GetEventCount())
print(testEvent1.GetEventCount())
print(testEvent2.GetEventCount())
print(testEvent3.GetEventCount())
print(testEvent4.GetEventCount())
print(testEvent5.GetEventCount())
print(testEvent6.GetEventCount())
print(testEvent7.GetEventCount())
print(testEvent8.GetEventCount())
print(testEvent9.GetEventCount())
print(testEvent10.GetEventCount())

particleNumberCut = ParticleNumberZA()
vbsCut = StandardVBFCut(True, 150.0, 1.2)
invllCut = EllInvMass(10, 91.1876)
ellDotCut = DotEllCut(0.7)
mzaCut = SHatZACut(300, -1)

CutEvents(testEvent0, particleNumberCut)
CutEvents(testEvent1, particleNumberCut)
CutEvents(testEvent2, particleNumberCut)
CutEvents(testEvent3, particleNumberCut)
CutEvents(testEvent4, particleNumberCut)
CutEvents(testEvent5, particleNumberCut)
CutEvents(testEvent6, particleNumberCut)
CutEvents(testEvent7, particleNumberCut)
CutEvents(testEvent8, particleNumberCut)
CutEvents(testEvent9, particleNumberCut)
CutEvents(testEvent10, particleNumberCut)

print(testEvent0.GetEventCount())
print(testEvent1.GetEventCount())
print(testEvent2.GetEventCount())
print(testEvent3.GetEventCount())
print(testEvent4.GetEventCount())
print(testEvent5.GetEventCount())
print(testEvent6.GetEventCount())
print(testEvent7.GetEventCount())
print(testEvent8.GetEventCount())
print(testEvent9.GetEventCount())
print(testEvent10.GetEventCount())

CutEvents(testEvent0, invllCut)
CutEvents(testEvent1, invllCut)
CutEvents(testEvent2, invllCut)
CutEvents(testEvent3, invllCut)
CutEvents(testEvent4, invllCut)
CutEvents(testEvent5, invllCut)
CutEvents(testEvent6, invllCut)
CutEvents(testEvent7, invllCut)
CutEvents(testEvent8, invllCut)
CutEvents(testEvent9, invllCut)
CutEvents(testEvent10, invllCut)

print(testEvent0.GetEventCount())
print(testEvent1.GetEventCount())
print(testEvent2.GetEventCount())
print(testEvent3.GetEventCount())
print(testEvent4.GetEventCount())
print(testEvent5.GetEventCount())
print(testEvent6.GetEventCount())
print(testEvent7.GetEventCount())
print(testEvent8.GetEventCount())
print(testEvent9.GetEventCount())
print(testEvent10.GetEventCount())

CutEvents(testEvent0, ellDotCut)
CutEvents(testEvent1, ellDotCut)
CutEvents(testEvent2, ellDotCut)
CutEvents(testEvent3, ellDotCut)
CutEvents(testEvent4, ellDotCut)
CutEvents(testEvent5, ellDotCut)
CutEvents(testEvent6, ellDotCut)
CutEvents(testEvent7, ellDotCut)
CutEvents(testEvent8, ellDotCut)
CutEvents(testEvent9, ellDotCut)
CutEvents(testEvent10, ellDotCut)

print(testEvent0.GetEventCount())
print(testEvent1.GetEventCount())
print(testEvent2.GetEventCount())
print(testEvent3.GetEventCount())
print(testEvent4.GetEventCount())
print(testEvent5.GetEventCount())
print(testEvent6.GetEventCount())
print(testEvent7.GetEventCount())
print(testEvent8.GetEventCount())
print(testEvent9.GetEventCount())
print(testEvent10.GetEventCount())

CutEvents(testEvent0, vbsCut)
CutEvents(testEvent1, vbsCut)
CutEvents(testEvent2, vbsCut)
CutEvents(testEvent3, vbsCut)
CutEvents(testEvent4, vbsCut)
CutEvents(testEvent5, vbsCut)
CutEvents(testEvent6, vbsCut)
CutEvents(testEvent7, vbsCut)
CutEvents(testEvent8, vbsCut)
CutEvents(testEvent9, vbsCut)
CutEvents(testEvent10, vbsCut)

print(testEvent0.GetEventCount())
print(testEvent1.GetEventCount())
print(testEvent2.GetEventCount())
print(testEvent3.GetEventCount())
print(testEvent4.GetEventCount())
print(testEvent5.GetEventCount())
print(testEvent6.GetEventCount())
print(testEvent7.GetEventCount())
print(testEvent8.GetEventCount())
print(testEvent9.GetEventCount())
print(testEvent10.GetEventCount())
